name: 'Nimbus Modules'
type: module
description: Module configuration support for the nimbus config extension.
# core: 8.x

# Information added by Drupal.org packaging script on 2016-10-19
version: '8.x-1.x-dev'
core: '8.x'
project: 'nimbus'
datestamp: 1476861540
